### ISSUE TITLE
Smarty 2+ incompatibility

### ISSUE THREAD

**Issue by jofranz** [systopia/de.systopia.osm#44]
Affected version: `1.6.1` (latest)
```
Fatal error: Uncaught Error: Cannot access protected property Smarty\Smarty::$template_dir in [...]/drupal/vendor/civicrm/civicrm-packages/smarty5/Smarty.php:37
Stack trace:
#0 [...]/drupal/web/sites/default/civicrm-extensions/de.systopia.osm/osm.civix.php(99): Smarty->__get('template_dir')
#1 [...]/drupal/web/sites/default/civicrm-extensions/de.systopia.osm/osm.php(32): _osm_civix_civicrm_config(Object(CRM_Core_Config))
#2 [...]/drupal/vendor/civicrm/civicrm-core/CRM/Utils/Hook.php(276): osm_civicrm_config(Object(CRM_Core_Config), Array)
#3 [...]/drupal/vendor/civicrm/civicrm-core/CRM/Utils/Hook/DrupalBase.php(73): CRM_Utils_Hook->runHooks(Array, 'civicrm_config', 2, Object(CRM_Core_Config), Array, NULL, NULL, NULL, NULL)
#4 [...]/drupal/vendor/civicrm/civ in [...]/drupal/vendor/civicrm/civicrm-packages/smarty5/Smarty.php on line 37
================================================================================
```

Might be fixable by #29

**Comment by tresero** [comment]
This was annoying me, so I fixed it (I think, please test though)

Here is the diff.

[fix-template-dir-issue.patch](https://github.com/user-attachments/files/18461891/fix-template-dir-issue.patch)

**Comment by jofranz** [comment]
Do you think this might also be fixable by a civix update? I'm asking as we tend to not change `civix` files as they are auto-generated.

**Comment by tresero** [comment]
> Do you think this might also be fixable by a civix update? I'm asking as we tend to not change `civix` files as they are auto-generated.

I have no idea. I just got sick of seeing the warnings in my logs.

**Comment by ufundo** [comment]
>Do you think this might also be fixable by a civix update? 

Yes - a `civix update` should be all that is required to fix this

**Comment by bjendres** [comment]
Is this still relevant? Feel free to re-open
