### ISSUE TITLE
Nominatim sends "Network is unreachable (101)"

### ISSUE THREAD

**Issue by bjendres** [systopia/de.systopia.osm#8]
If you exceed your quota with Nominatim you get a reply giving an appropriate error message. But  apparently if you still keep on contacting them excessively, you will eventually be blocked completely.

Unfortunately that causes an error in the extension that ultimately stops the address geocoding and also the currently ongoing address change.

Here's a typical stack trace:

```
#0 /var/www/sites/all/modules/civicrm/CRM/Core/Error.php(897): CRM_Core_Error::backtrace("backTrace", TRUE)
#1 [internal function](): CRM_Core_Error::exceptionHandler(Object(PEAR_Error))
#2 /var/www/sites/all/modules/civicrm/packages/PEAR.php(931): call_user_func((Array:2), Object(PEAR_Error))
#3 /var/www/sites/all/modules/civicrm/packages/PEAR.php(566): PEAR_Error->PEAR_Error("Network is unreachable", 101, 16, (Array:2), NULL)
#4 /var/www/sites/all/modules/civicrm/packages/Net/Socket.php(156): PEAR->raiseError("Network is unreachable", 101)
#5 /var/www/sites/all/modules/civicrm/packages/HTTP/Request.php(737): Net_Socket->connect("ssl://nominatim.openstreetmap.org", 443, NULL, NULL, NULL)
#6 /var/www/sites/default/civicrm-extensions/de.systopia.osm/CRM/Utils/Geocode/OpenStreetMapCoding.php(140): HTTP_Request->sendRequest()
#7 /var/www/sites/all/modules/civicrm/CRM/Core/BAO/Address.php(397): CRM_Utils_Geocode_OpenStreetMapCoding::format((Array:10))
#8 /var/www/sites/all/modules/civicrm/CRM/Core/BAO/Address.php(152): CRM_Core_BAO_Address::fixAddress((Array:10))
#9 /var/www/sites/all/modules/civicrm/api/v3/Address.php(75): CRM_Core_BAO_Address::add((Array:10), TRUE)
#10 /var/www/sites/all/modules/civicrm/Civi/API/Provider/MagicFunctionProvider.php(89): civicrm_api3_address_create((Array:10))
#11 /var/www/sites/all/modules/civicrm/Civi/API/Kernel.php(96): Civi\API\Provider\MagicFunctionProvider->invoke((Array:9))
#12 /var/www/sites/all/modules/civicrm/api/api.php(23): Civi\API\Kernel->run("Address", "create", (Array:9), NULL)
#13 /var/www/sites/all/modules/civicrm/api/api.php(43): civicrm_api("Address", "create", (Array:9))
[...]
```

**Comment by niels-heinemann** [comment]
I ran into this. How to avoid? 

Catching the error seems to work around for the moment.

``` php
    $result = null;
    try {
        $request = new HTTP_Request($url);
        $result = $request->sendRequest();
    }
    catch(Exception $e) {
      CRM_Core_Error::debug_log_message('Geocoding failed: ' . $e->getMessage());
      return FALSE;
    }
```

**Comment by bjendres** [comment]
Hi @nielosz:

> I ran into this. How to avoid?

I think your options are limited:
1. less requests. Ideally stop for a day when you receive the "quota exceeded" message.
2. talk to nominatim
3. use another openstreetmap service

And thanks for the code snippet, we'll address this soon - probably using this.

**Comment by bjendres** [comment]
seems to be working fine.
